k8sServiceHost: "API-SERVER-IP"
k8sServicePort: "6443"

# -- Install the cilium agent resources.
agent: true

# -- Agent container name.
name: cilium

# Increase rate limit when doing L2 announcements
k8sClientRateLimit:
  qps: 50
  burst: 100

# -- Roll out cilium agent pods automatically when configmap is updated.
rollOutCiliumPods: true

cni:
  install: true
  # -- Remove the CNI configuration and binary files on agent shutdown. Enable this
  # if you're removing Cilium from the cluster. Disable this to prevent the CNI
  # configuration file from being removed during agent upgrade, which can cause
  # nodes to go unmanageable.
  uninstall: false

envoyConfig:
  enabled: true

# Enable envoy daemonset
envoy:
  enabled: true

# Enable prometheus metrics for cilium-envoy
  prometheus:
    enabled: false
    serviceMonitor:
      enabled: false

# Enable Layer 7 network policy.
l7Proxy: true

gatewayAPI:
  enabled: false

ingressController:
  enabled: false

k8sNetworkPolicy:
  # -- Enable support for K8s NetworkPolicy
  enabled: true

endpointRoutes:
  enabled: true

hubble:
  enabled: true

  relay:
    enabled: true

    # -- Roll out Hubble Relay pods automatically when configmap is updated.
    rollOutPods: true

    # -- Enable prometheus metrics for hubble-relay on the configured port at
    # /metrics
    prometheus:
      enabled: false
      serviceMonitor:
        enabled: false

  ui:
    enabled: true
    rollOutPods: true

kubeProxyReplacement: true

ipam:
  mode: "kubernetes"

ipv4:
  enabled: true

routingMode: "native"
autoDirectNodeRoutes: true
ipv4NativeRoutingCIDR: "10.40.0.0/16"
requireIPv4PodCIDR: true

bpf:
  masquerade: true
  hostLegacyRouting: true

# -- Enables masquerading of IPv4 traffic leaving the node from endpoints.
enableIPv4Masquerade: true

# -- Configure prometheus metrics on the configured port at /metrics
prometheus:
  enabled: false
  serviceMonitor:
    enabled: false

operator:
  enabled: true

  # -- Roll out cilium-operator pods automatically when configmap is updated.
  rollOutPods: true

  # -- Number of replicas to run for the cilium-operator deployment
  replicas: 1

  # -- Enable prometheus metrics for cilium-operator on the configured port at
  prometheus:
    enabled: false
    serviceMonitor:
      enabled: false

policyAuditMode: false
