---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cert@example.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          route53:
            accessKeyID: ACCESS-KEY
            region: eu-central-1
            secretAccessKeySecretRef:
              key: secret-access-key
              name: route53-credentials-secret
